from tkinter import*
window=Tk()
window.title("Генератор паролей")
window.geometry("400x400")
simbols=LabelFrame(window,text="Символы",font="Arial 12")
lowercase=BooleanVar()
numbers=BooleanVar()
uppercase=BooleanVar()
simbols1=BooleanVar()
check_lowercase=Checkbutton(simbols,text="abcdefghijklmnopqrstuvwxyz",variable=lowercase,onvalue=True,offvalue=False)
check_numbers=Checkbutton(simbols,text="0123456789",variable=numbers,onvalue=True,offvalue=False)
check_uppercase=Checkbutton(simbols,text="ABCDEFGHIJKLMNOPQRSTUVWXYZ",variable=uppercase,onvalue=True,offvalue=False)
check_simbols=Checkbutton(simbols,text="!@#$%^&*()",variable=simbols1,onvalue=True,offvalue=False)
l_b=Listbox(simbols,height=5)
button=Button(simbols,text="Сгенерировать пароль",)
frame=Frame()
lb=Label(frame,text="Количество строчных букв:\nКоличество цифр:\nКоличество заглавных букв:\nКоличество символов:",font=("Arial,9"))
en1=Entry(frame,width=1,font=("Arial",10))
en2=Entry(frame,width=1,font=("Arial",10))
en3=Entry(frame,width=1,font=("Arial",10))
en4=Entry(frame,width=1,font=("Arial",10))
simbols.pack(pady=10)
check_lowercase.pack(anchor="w")
check_numbers.pack(anchor="w")
check_uppercase.pack(anchor="w")
check_simbols.pack(anchor="w")
l_b.pack()
button.pack()
frame.pack()
lb.grid(rowspan=10,row=0,column=0)
en1.grid(row=0,column=1)
en2.grid(row=1,column=1)
en3.grid(row=2,column=1)
en4.grid(row=3,column=1)