from tkinter import*
from tkinter import messagebox
window=Tk()
window.title("Генератор паролей")
window.geometry("400x300")
simbols=LabelFrame(window,text="Символы",font="Arial 12")
lowercase=BooleanVar()
numbers=BooleanVar()
uppercase=BooleanVar()
simbols1=BooleanVar()
check_lowercase=Checkbutton(simbols,text="abcdefghijklmnopqrstuvwxyz",variable=lowercase,onvalue=True,offvalue=False)
check_numbers=Checkbutton(simbols,text="0123456789",variable=numbers,onvalue=True,offvalue=False)
check_uppercase=Checkbutton(simbols,text="ABCDEFGHIJKLMNOPQRSTUVWXYZ",variable=uppercase,onvalue=True,offvalue=False)
check_simbols=Checkbutton(simbols,text="!@#$%^&*()",variable=simbols1,onvalue=True,offvalue=False)
l_b=Listbox(simbols,height=5)
button=Button(simbols,text="Сгенерировать пароль",)
simbols.pack(pady=10)
check_lowercase.pack(anchor="w")
check_numbers.pack(anchor="w")
check_uppercase.pack(anchor="w")
check_simbols.pack(anchor="w")
l_b.pack()
button.pack()
if __name__=="__main__":
    window.mainloop()